### PR TITLE
Add RO-Crate and FAIRSharing initiatives to about page

### PR DESCRIPTION
**Pull request by stain**

### CODE REVIEW

**Comment by martin-nc** [comment]
@stain I had to refer this to the BY-COVID project management. They have decided that the 'Global initiatives' section should be removed for now. They may want to reinstate it when there are clear criteria which resources should be included in this section. I believe these might come out of the work of WP6 of the project.

So I will close this PR and remove the Global initiatives section. Sorry about that.

**Comment by bgruening** [comment]
This is not good. Why is less information better here? Until there are clear guidelines we should be able to add them and not the other way around IMHO :)

**Comment by klauer2207** [comment]
Hello, I'm sorry this is disappointing news for now. When we designed the website we included initiatives that were mentioned in the original grant proposal. Since then we have not reviewed this and designed a process with criteria for inclusion and exclusion or re-evaluated if the terminology is still fit for purpose . Please give us some time to think this through.

**Comment by stain** [comment]
Perhaps a new subsection like _Related Resources_ would be more appropriate, so we don't need to sign formal collaboration agreements to list work done/supported by the BY-COVID project 

(btw both Fairsharing and RO-Crate are listed in proposal, and their leads are BY-COVID partners).

If we split like that, then there is still room to highlight signed strategic partnerships in a different section, e.g. as ELIXIR does on https://elixir-europe.org/collaborations

**Pull request closed without merging**
